// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4WjUDJLvB98xXRWRJk80pIIt2YqQsm4',
    appId: '1:681491080732:web:088c546ffac1a51af921d9',
    messagingSenderId: '681491080732',
    projectId: 'ecommerceapp-35b69',
    authDomain: 'ecommerceapp-35b69.firebaseapp.com',
    storageBucket: 'ecommerceapp-35b69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4Nf9LN8WbO0Q95rf5r-Pfwkf5NODT7s',
    appId: '1:681491080732:android:ae08eb7261741e46f921d9',
    messagingSenderId: '681491080732',
    projectId: 'ecommerceapp-35b69',
    storageBucket: 'ecommerceapp-35b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL_L0jkqae2jlCnWtMjpVf0-KpoDhkf3w',
    appId: '1:681491080732:ios:e2fe7c0985370979f921d9',
    messagingSenderId: '681491080732',
    projectId: 'ecommerceapp-35b69',
    storageBucket: 'ecommerceapp-35b69.appspot.com',
    androidClientId: '681491080732-t0uf1f26c55nq6k3kjeo2msld2mgu5pf.apps.googleusercontent.com',
    iosClientId: '681491080732-ncn9mu5c742i5aoeptt2jj3ugpkpgmsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseECommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL_L0jkqae2jlCnWtMjpVf0-KpoDhkf3w',
    appId: '1:681491080732:ios:e2fe7c0985370979f921d9',
    messagingSenderId: '681491080732',
    projectId: 'ecommerceapp-35b69',
    storageBucket: 'ecommerceapp-35b69.appspot.com',
    androidClientId: '681491080732-t0uf1f26c55nq6k3kjeo2msld2mgu5pf.apps.googleusercontent.com',
    iosClientId: '681491080732-ncn9mu5c742i5aoeptt2jj3ugpkpgmsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseECommerceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-pBsAyM1hT8gRSbQqWhT8dQCzGHvpvis',
    appId: '1:681491080732:web:5aae1e8d96d334d9f921d9',
    messagingSenderId: '681491080732',
    projectId: 'ecommerceapp-35b69',
    authDomain: 'ecommerceapp-35b69.firebaseapp.com',
    storageBucket: 'ecommerceapp-35b69.appspot.com',
  );
}
